import java.util.Date;

public class Customer {
    private String id; // Typically generated by the database, so not included in the constructor
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private String sex;
    private Date birthday; // Assuming java.util.Date for simplicity
    private String password; // Plaintext password, to be hashed before storage
    private String hashedPassword;


    // Constructor without ID, as it's auto-generated by the database
    public Customer(String firstName, String lastName, String email, String phone, String sex, Date birthday, String password, String hashedPassword) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.sex = sex;
        this.birthday = birthday;
        this.password = password;
        this.hashedPassword = hashedPassword;
    }

    // Getters and setters for all fields
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id; // Allow setting the ID after object creation, as it's generated by the database
    }

    // Implement the rest of the getters and setters...

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }


    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    // Other getters and setters for firstName, lastName, email, phone, sex, birthday
}
